// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_RangeError_HeaderFile
#include <Standard_RangeError.hxx>
#endif
#ifndef _Standard_DimensionMismatch_HeaderFile
#include <Standard_DimensionMismatch.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_OutOfMemory_HeaderFile
#include <Standard_OutOfMemory.hxx>
#endif
#ifndef _StepVisual_CameraModelD3MultiClippingUnionSelect_HeaderFile
#include <StepVisual_CameraModelD3MultiClippingUnionSelect.hxx>
#endif
#ifndef _StepVisual_Array1OfCameraModelD3MultiClippingUnionSelect_HeaderFile
#include <StepVisual_Array1OfCameraModelD3MultiClippingUnionSelect.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect)


IMPLEMENT_DOWNCAST(StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect)


#define ItemHArray1 StepVisual_CameraModelD3MultiClippingUnionSelect
#define ItemHArray1_hxx <StepVisual_CameraModelD3MultiClippingUnionSelect.hxx>
#define TheArray1 StepVisual_Array1OfCameraModelD3MultiClippingUnionSelect
#define TheArray1_hxx <StepVisual_Array1OfCameraModelD3MultiClippingUnionSelect.hxx>
#define TCollection_HArray1 StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect
#define TCollection_HArray1_hxx <StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect.hxx>
#define Handle_TCollection_HArray1 Handle_StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect
#define TCollection_HArray1_Type_() StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect_Type_()
//#include <TCollection_HArray1.gxx>

