// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <StepDimTol_HArray1OfToleranceZoneTarget.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_RangeError_HeaderFile
#include <Standard_RangeError.hxx>
#endif
#ifndef _Standard_DimensionMismatch_HeaderFile
#include <Standard_DimensionMismatch.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_OutOfMemory_HeaderFile
#include <Standard_OutOfMemory.hxx>
#endif
#ifndef _StepDimTol_ToleranceZoneTarget_HeaderFile
#include <StepDimTol_ToleranceZoneTarget.hxx>
#endif
#ifndef _StepDimTol_Array1OfToleranceZoneTarget_HeaderFile
#include <StepDimTol_Array1OfToleranceZoneTarget.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(StepDimTol_HArray1OfToleranceZoneTarget)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepDimTol_HArray1OfToleranceZoneTarget)


IMPLEMENT_DOWNCAST(StepDimTol_HArray1OfToleranceZoneTarget,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepDimTol_HArray1OfToleranceZoneTarget)


#define ItemHArray1 Handle_StepDimTol_ToleranceZoneTarget
#define ItemHArray1_hxx <StepDimTol_ToleranceZoneTarget.hxx>
#define TheArray1 StepDimTol_Array1OfToleranceZoneTarget
#define TheArray1_hxx <StepDimTol_Array1OfToleranceZoneTarget.hxx>
#define TCollection_HArray1 StepDimTol_HArray1OfToleranceZoneTarget
#define TCollection_HArray1_hxx <StepDimTol_HArray1OfToleranceZoneTarget.hxx>
#define Handle_TCollection_HArray1 Handle_StepDimTol_HArray1OfToleranceZoneTarget
#define TCollection_HArray1_Type_() StepDimTol_HArray1OfToleranceZoneTarget_Type_()
//#include <TCollection_HArray1.gxx>

