// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <StepDimTol_Array1OfDatumReferenceModifier.hxx>

#ifndef _Standard_RangeError_HeaderFile
#include <Standard_RangeError.hxx>
#endif
#ifndef _Standard_DimensionMismatch_HeaderFile
#include <Standard_DimensionMismatch.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_OutOfMemory_HeaderFile
#include <Standard_OutOfMemory.hxx>
#endif
#ifndef _StepDimTol_DatumReferenceModifier_HeaderFile
#include <StepDimTol_DatumReferenceModifier.hxx>
#endif
 

#define Array1Item Handle_StepDimTol_DatumReferenceModifier
#define Array1Item_hxx <StepDimTol_DatumReferenceModifier.hxx>
#define TCollection_Array1 StepDimTol_Array1OfDatumReferenceModifier
#define TCollection_Array1_hxx <StepDimTol_Array1OfDatumReferenceModifier.hxx>
//#include <TCollection_Array1.gxx>

