// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <StepRepr_HArray1OfShapeAspect.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_RangeError_HeaderFile
#include <Standard_RangeError.hxx>
#endif
#ifndef _Standard_DimensionMismatch_HeaderFile
#include <Standard_DimensionMismatch.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_OutOfMemory_HeaderFile
#include <Standard_OutOfMemory.hxx>
#endif
#ifndef _StepRepr_ShapeAspect_HeaderFile
#include <StepRepr_ShapeAspect.hxx>
#endif
#ifndef _StepRepr_Array1OfShapeAspect_HeaderFile
#include <StepRepr_Array1OfShapeAspect.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(StepRepr_HArray1OfShapeAspect)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepRepr_HArray1OfShapeAspect)


IMPLEMENT_DOWNCAST(StepRepr_HArray1OfShapeAspect,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepRepr_HArray1OfShapeAspect)


#define ItemHArray1 Handle_StepRepr_ShapeAspect
#define ItemHArray1_hxx <StepRepr_ShapeAspect.hxx>
#define TheArray1 StepRepr_Array1OfShapeAspect
#define TheArray1_hxx <StepRepr_Array1OfShapeAspect.hxx>
#define TCollection_HArray1 StepRepr_HArray1OfShapeAspect
#define TCollection_HArray1_hxx <StepRepr_HArray1OfShapeAspect.hxx>
#define Handle_TCollection_HArray1 Handle_StepRepr_HArray1OfShapeAspect
#define TCollection_HArray1_Type_() StepRepr_HArray1OfShapeAspect_Type_()
//#include <TCollection_HArray1.gxx>

