// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_XCAFDimTolObjects_DatumObject_HeaderFile
#define _Handle_XCAFDimTolObjects_DatumObject_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif


class Standard_Transient;
class Handle(Standard_Type);
class XCAFDimTolObjects_DatumObject;

DEFINE_STANDARD_HANDLE(XCAFDimTolObjects_DatumObject,Standard_Transient)

#endif
