// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_IGESGraph_LineFontPredefined_HeaderFile
#define _Handle_IGESGraph_LineFontPredefined_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_IGESData_IGESEntity_HeaderFile
#include <Handle_IGESData_IGESEntity.hxx>
#endif

#ifndef _IGESData_LineFontEntity_HeaderFile
#include <IGESData_LineFontEntity.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(IGESData_IGESEntity);
class Handle(IGESData_LineFontEntity);
class IGESGraph_LineFontPredefined;

DEFINE_STANDARD_HANDLE(IGESGraph_LineFontPredefined,IGESData_LineFontEntity)

#endif
