// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_StepRepr_ReprItemAndLengthMeasureWithUnit_HeaderFile
#define _Handle_StepRepr_ReprItemAndLengthMeasureWithUnit_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef StepRepr_ReprItemAndMeasureWithUnit_HeaderFile
#include <StepRepr_ReprItemAndMeasureWithUnit.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(StepRepr_ReprItemAndMeasureWithUnit);
class StepRepr_ReprItemAndLengthMeasureWithUnit;

DEFINE_STANDARD_HANDLE(StepRepr_ReprItemAndLengthMeasureWithUnit, StepRepr_ReprItemAndMeasureWithUnit)

#endif
