// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepAP242_TessellatedShapeRepresentation_HeaderFile
#define _StepAP242_TessellatedShapeRepresentation_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Handle.hxx>

#include <StepShape_ShapeRepresentation.hxx>


DEFINE_STANDARD_HANDLE(StepAP242_TessellatedShapeRepresentation, StepShape_ShapeRepresentation);
class StepAP242_TessellatedShapeRepresentation : public StepShape_ShapeRepresentation {

public:

  //! Returns a AdvancedBrepShapeRepresentation <br>
  Standard_EXPORT   StepAP242_TessellatedShapeRepresentation();




  DEFINE_STANDARD_RTTIEXT(StepAP242_TessellatedShapeRepresentation,StepShape_ShapeRepresentation);

protected:




private: 




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
