// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepAP242_TessellatedShell_HeaderFile
#define _StepAP242_TessellatedShell_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Handle.hxx>

#include <StepShape_TopologicalRepresentationItem.hxx>
#include <StepAP242_TessellatedSurface.hxx>
#include <NCollection_Array1.hxx>
#include <NCollection_Handle.hxx>

#include <StepShape_Shell.hxx>

class Standard_Transient;
class StepShape_HArray1OfFace;
class TCollection_HAsciiString;
class StepShape_Face;


typedef NCollection_Array1<Handle(StepAP242_TessellatedSurface)> StepAP242_ArrayOfTessellatedSurface;

DEFINE_STANDARD_HANDLE(StepAP242_TessellatedShell, StepShape_TopologicalRepresentationItem);

class StepAP242_TessellatedShell : public StepShape_TopologicalRepresentationItem {

public:

  //! Returns a ConnectedFaceSet <br>
  Standard_EXPORT   StepAP242_TessellatedShell();
  
  Standard_EXPORT   void Init(const Handle(TCollection_HAsciiString)& aName, const NCollection_Handle<StepAP242_ArrayOfTessellatedSurface>& aComplexTriangulatedSurfaces, const StepShape_Shell& aShell);
  
  Standard_EXPORT   NCollection_Handle<StepAP242_ArrayOfTessellatedSurface> TesslatedSurfaces() const;
  
  Standard_EXPORT   Handle_StepAP242_TessellatedSurface TesslatedSurface(const Standard_Integer num) const;
  
  Standard_EXPORT   Standard_Integer NbTesslatedSurface() const;

  Standard_EXPORT   StepShape_Shell Shell() const;


protected:
  StepShape_Shell myShell;
  NCollection_Handle<StepAP242_ArrayOfTessellatedSurface> mySurfaces;



public: 

  DEFINE_STANDARD_RTTIEXT(StepAP242_TessellatedShell,StepShape_TopologicalRepresentationItem);

};

#endif
