// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepRepr_GeneralPropertyAssociation_HeaderFile
#define _StepRepr_GeneralPropertyAssociation_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_StepBasic_GeneralProperty_HeaderFile
#include <Handle_StepBasic_GeneralProperty.hxx>
#endif
#ifndef _StepRepr_PropertySelect_HeaderFile
#include <StepRepr_PropertySelect.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
#ifndef _StepBasic_GeneralProperty_HeaderFile
#include <StepBasic_GeneralProperty.hxx>
#endif

class StepBasic_GeneralProperty;
class StepRepr_PropertySelect;

DEFINE_STANDARD_HANDLE(StepRepr_GeneralPropertyAssociation, MMgt_TShared);

//! Representation of STEP entity RoleAssociation <br>
class StepRepr_GeneralPropertyAssociation : public MMgt_TShared {

public:

  //! Empty constructor <br>
  Standard_EXPORT   StepRepr_GeneralPropertyAssociation();
  //! Initialize all fields (own and inherited) <br>
  Standard_EXPORT     void Init(const Handle(TCollection_HAsciiString)& theName, const Handle(TCollection_HAsciiString)& theDesc, const Handle(StepBasic_GeneralProperty)& aProperty, const StepRepr_PropertySelect& aItemWithProperty);
  //! Returns field Property <br>
  Standard_EXPORT     Handle_StepBasic_GeneralProperty Property() const;
  //! Set field Role <br>
  Standard_EXPORT     void SetProperty(const Handle(StepBasic_GeneralProperty)& aProperty) ;
  //! Returns field ItemWithRole <br>
  Standard_EXPORT     StepRepr_PropertySelect ItemWithProperty() const;
  //! Set field ItemWithRole <br>
  Standard_EXPORT     void SetItemWithProperty(const StepRepr_PropertySelect& aItemWithProperty) ;
  Standard_EXPORT Handle(TCollection_HAsciiString) Name() const;
  Standard_EXPORT Handle(TCollection_HAsciiString) Desc() const;




  DEFINE_STANDARD_RTTIEXT(StepRepr_GeneralPropertyAssociation,MMgt_TShared);

protected:




private: 

	Handle(TCollection_HAsciiString) myName;
	Handle(TCollection_HAsciiString) myDesc;
Handle_StepBasic_GeneralProperty myProperty;
StepRepr_PropertySelect myItemWithProperty;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
