// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepRepr_PropertySelect_HeaderFile
#define _StepRepr_PropertySelect_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _StepData_SelectType_HeaderFile
#include <StepData_SelectType.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Handle_Standard_Transient_HeaderFile
#include <Handle_Standard_Transient.hxx>
#endif
#ifndef _StepRepr_PropertyDefinition_HeaderFile
#include <StepRepr_PropertyDefinition.hxx>
#endif

class StepRepr_PropertyDefinition;


//! Representation of STEP SELECT type RoleSelect <br>
class StepRepr_PropertySelect  : public StepData_SelectType {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  //! Empty constructor <br>
  Standard_EXPORT   StepRepr_PropertySelect();
  //! Recognizes a kind of RoleSelect select type <br>
//!          1 -> PropertyDefinition <br>
//!          0 else <br>
  Standard_EXPORT     Standard_Integer CaseNum(const Handle(Standard_Transient)& ent) const;
  //! Returns Value as PropertyDefinition (or Null if another type) <br>
  Standard_EXPORT     Handle_StepRepr_PropertyDefinition PropertyDefinition() const;


protected:





private:





};





// other Inline functions and methods (like "C++: function call" methods)


#endif
